/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MyHostedEventsRouteImport } from './routes/my-hosted-events'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as EventsCreateRouteImport } from './routes/events/create'
import { Route as DashboardPathlessLayoutRouteImport } from './routes/dashboard/_pathlessLayout'
import { Route as DashboardOverviewRouteImport } from './routes/dashboard/Overview'
import { Route as AdminsUsersRouteImport } from './routes/admins/users'
import { Route as AdminsDashboardRouteImport } from './routes/admins/dashboard'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/Login'

const DashboardRouteImport = createFileRoute('/dashboard')()

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MyHostedEventsRoute = MyHostedEventsRouteImport.update({
  id: '/my-hosted-events',
  path: '/my-hosted-events',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const EventsCreateRoute = EventsCreateRouteImport.update({
  id: '/events/create',
  path: '/events/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPathlessLayoutRoute = DashboardPathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: '/dashboard/Overview',
  path: '/dashboard/Overview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsUsersRoute = AdminsUsersRouteImport.update({
  id: '/admins/users',
  path: '/admins/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsDashboardRoute = AdminsDashboardRouteImport.update({
  id: '/admins/dashboard',
  path: '/admins/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/Login',
  path: '/Login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-events': typeof MyEventsRoute
  '/my-hosted-events': typeof MyHostedEventsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/Login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/admins/dashboard': typeof AdminsDashboardRoute
  '/admins/users': typeof AdminsUsersRoute
  '/dashboard/Overview': typeof DashboardOverviewRoute
  '/dashboard': typeof DashboardPathlessLayoutRoute
  '/events/create': typeof EventsCreateRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events': typeof EventsIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-events': typeof MyEventsRoute
  '/my-hosted-events': typeof MyHostedEventsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/Login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/admins/dashboard': typeof AdminsDashboardRoute
  '/admins/users': typeof AdminsUsersRoute
  '/dashboard/Overview': typeof DashboardOverviewRoute
  '/dashboard': typeof DashboardIndexRoute
  '/events/create': typeof EventsCreateRoute
  '/events': typeof EventsIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my-events': typeof MyEventsRoute
  '/my-hosted-events': typeof MyHostedEventsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/(auth)/Login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/admins/dashboard': typeof AdminsDashboardRoute
  '/admins/users': typeof AdminsUsersRoute
  '/dashboard/Overview': typeof DashboardOverviewRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/_pathlessLayout': typeof DashboardPathlessLayoutRoute
  '/events/create': typeof EventsCreateRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events/': typeof EventsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/my-events'
    | '/my-hosted-events'
    | '/privacy'
    | '/terms'
    | '/Login'
    | '/register'
    | '/admins/dashboard'
    | '/admins/users'
    | '/dashboard/Overview'
    | '/dashboard'
    | '/events/create'
    | '/dashboard/'
    | '/events'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/my-events'
    | '/my-hosted-events'
    | '/privacy'
    | '/terms'
    | '/Login'
    | '/register'
    | '/admins/dashboard'
    | '/admins/users'
    | '/dashboard/Overview'
    | '/dashboard'
    | '/events/create'
    | '/events'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/my-events'
    | '/my-hosted-events'
    | '/privacy'
    | '/terms'
    | '/(auth)/Login'
    | '/(auth)/register'
    | '/admins/dashboard'
    | '/admins/users'
    | '/dashboard/Overview'
    | '/dashboard'
    | '/dashboard/_pathlessLayout'
    | '/events/create'
    | '/dashboard/'
    | '/events/'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyEventsRoute: typeof MyEventsRoute
  MyHostedEventsRoute: typeof MyHostedEventsRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  AdminsDashboardRoute: typeof AdminsDashboardRoute
  AdminsUsersRoute: typeof AdminsUsersRoute
  DashboardOverviewRoute: typeof DashboardOverviewRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EventsCreateRoute: typeof EventsCreateRoute
  EventsIndexRoute: typeof EventsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-hosted-events': {
      id: '/my-hosted-events'
      path: '/my-hosted-events'
      fullPath: '/my-hosted-events'
      preLoaderRoute: typeof MyHostedEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/events/create': {
      id: '/events/create'
      path: '/events/create'
      fullPath: '/events/create'
      preLoaderRoute: typeof EventsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_pathlessLayout': {
      id: '/dashboard/_pathlessLayout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardPathlessLayoutRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/Overview': {
      id: '/dashboard/Overview'
      path: '/dashboard/Overview'
      fullPath: '/dashboard/Overview'
      preLoaderRoute: typeof DashboardOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admins/users': {
      id: '/admins/users'
      path: '/admins/users'
      fullPath: '/admins/users'
      preLoaderRoute: typeof AdminsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admins/dashboard': {
      id: '/admins/dashboard'
      path: '/admins/dashboard'
      fullPath: '/admins/dashboard'
      preLoaderRoute: typeof AdminsDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/Login': {
      id: '/(auth)/Login'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardPathlessLayoutRoute: typeof DashboardPathlessLayoutRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardPathlessLayoutRoute: DashboardPathlessLayoutRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyEventsRoute: MyEventsRoute,
  MyHostedEventsRoute: MyHostedEventsRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  AdminsDashboardRoute: AdminsDashboardRoute,
  AdminsUsersRoute: AdminsUsersRoute,
  DashboardOverviewRoute: DashboardOverviewRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EventsCreateRoute: EventsCreateRoute,
  EventsIndexRoute: EventsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
