/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MyHostedEventsRouteImport } from './routes/my-hosted-events'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as EventsCreateRouteImport } from './routes/events/create'
import { Route as AdminsUsersRouteImport } from './routes/admins/users'
import { Route as AdminsDashboardRouteImport } from './routes/admins/dashboard'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/Login'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/users/index'
import { Route as DashboardEventsIndexRouteImport } from './routes/dashboard/events/index'
import { Route as DashboardUsersIdRouteImport } from './routes/dashboard/users/$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MyHostedEventsRoute = MyHostedEventsRouteImport.update({
  id: '/my-hosted-events',
  path: '/my-hosted-events',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const EventsCreateRoute = EventsCreateRouteImport.update({
  id: '/events/create',
  path: '/events/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsUsersRoute = AdminsUsersRouteImport.update({
  id: '/admins/users',
  path: '/admins/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsDashboardRoute = AdminsDashboardRouteImport.update({
  id: '/admins/dashboard',
  path: '/admins/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/Login',
  path: '/Login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsIndexRoute = DashboardEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersIdRoute = DashboardUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/my-events': typeof MyEventsRoute
  '/my-hosted-events': typeof MyHostedEventsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/Login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/admins/dashboard': typeof AdminsDashboardRoute
  '/admins/users': typeof AdminsUsersRoute
  '/events/create': typeof EventsCreateRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events': typeof EventsIndexRoute
  '/dashboard/users/$id': typeof DashboardUsersIdRoute
  '/dashboard/events': typeof DashboardEventsIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-events': typeof MyEventsRoute
  '/my-hosted-events': typeof MyHostedEventsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/Login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/admins/dashboard': typeof AdminsDashboardRoute
  '/admins/users': typeof AdminsUsersRoute
  '/events/create': typeof EventsCreateRoute
  '/dashboard': typeof DashboardIndexRoute
  '/events': typeof EventsIndexRoute
  '/dashboard/users/$id': typeof DashboardUsersIdRoute
  '/dashboard/events': typeof DashboardEventsIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/my-events': typeof MyEventsRoute
  '/my-hosted-events': typeof MyHostedEventsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/(auth)/Login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/admins/dashboard': typeof AdminsDashboardRoute
  '/admins/users': typeof AdminsUsersRoute
  '/events/create': typeof EventsCreateRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events/': typeof EventsIndexRoute
  '/dashboard/users/$id': typeof DashboardUsersIdRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/my-events'
    | '/my-hosted-events'
    | '/privacy'
    | '/terms'
    | '/Login'
    | '/register'
    | '/admins/dashboard'
    | '/admins/users'
    | '/events/create'
    | '/dashboard/'
    | '/events'
    | '/dashboard/users/$id'
    | '/dashboard/events'
    | '/dashboard/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/my-events'
    | '/my-hosted-events'
    | '/privacy'
    | '/terms'
    | '/Login'
    | '/register'
    | '/admins/dashboard'
    | '/admins/users'
    | '/events/create'
    | '/dashboard'
    | '/events'
    | '/dashboard/users/$id'
    | '/dashboard/events'
    | '/dashboard/users'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/my-events'
    | '/my-hosted-events'
    | '/privacy'
    | '/terms'
    | '/(auth)/Login'
    | '/(auth)/register'
    | '/admins/dashboard'
    | '/admins/users'
    | '/events/create'
    | '/dashboard/'
    | '/events/'
    | '/dashboard/users/$id'
    | '/dashboard/events/'
    | '/dashboard/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  MyEventsRoute: typeof MyEventsRoute
  MyHostedEventsRoute: typeof MyHostedEventsRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  AdminsDashboardRoute: typeof AdminsDashboardRoute
  AdminsUsersRoute: typeof AdminsUsersRoute
  EventsCreateRoute: typeof EventsCreateRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-hosted-events': {
      id: '/my-hosted-events'
      path: '/my-hosted-events'
      fullPath: '/my-hosted-events'
      preLoaderRoute: typeof MyHostedEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/events/create': {
      id: '/events/create'
      path: '/events/create'
      fullPath: '/events/create'
      preLoaderRoute: typeof EventsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admins/users': {
      id: '/admins/users'
      path: '/admins/users'
      fullPath: '/admins/users'
      preLoaderRoute: typeof AdminsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admins/dashboard': {
      id: '/admins/dashboard'
      path: '/admins/dashboard'
      fullPath: '/admins/dashboard'
      preLoaderRoute: typeof AdminsDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/Login': {
      id: '/(auth)/Login'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events/': {
      id: '/dashboard/events/'
      path: '/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof DashboardEventsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users/$id': {
      id: '/dashboard/users/$id'
      path: '/users/$id'
      fullPath: '/dashboard/users/$id'
      preLoaderRoute: typeof DashboardUsersIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardUsersIdRoute: typeof DashboardUsersIdRoute
  DashboardEventsIndexRoute: typeof DashboardEventsIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardUsersIdRoute: DashboardUsersIdRoute,
  DashboardEventsIndexRoute: DashboardEventsIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  MyEventsRoute: MyEventsRoute,
  MyHostedEventsRoute: MyHostedEventsRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  AdminsDashboardRoute: AdminsDashboardRoute,
  AdminsUsersRoute: AdminsUsersRoute,
  EventsCreateRoute: EventsCreateRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
